# Generated by Django 4.0.3 on 2024-04-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.CharField(max_length=100)),
                ('arrival_time', models.CharField(max_length=100)),
                ('adult_fare', models.CharField(max_length=100)),
                ('child_fare', models.CharField(max_length=100)),
                ('student_fare', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('available_seats', models.CharField(max_length=100)),
            ],
        ),
    ]
