# Generated by Django 4.0.3 on 2024-04-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handML', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusInfo',
        ),
    ]
