# Generated by Django 5.0.6 on 2024-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busInfo', '0002_busschedule_rename_adult_fare_businfo_bus_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='t1_weekday_times',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='t1_weekend_times',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='t2_weekday_times',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='t2_weekend_times',
            field=models.TextField(null=True),
        ),
    ]
