# Generated by Django 5.0.6 on 2024-06-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busInfo', '0005_bus_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='fare',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
